/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panel;

import QuanLySinhVien.Check;
import QuanLySinhVien.SinhVien;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DMX PHO THANH
 */
public class frmSvien extends javax.swing.JPanel {

    /**
     * Creates new form frmSvien
     */
    public frmSvien() {
        initComponents();
        try {
            DbKetNoi.Db.getConnection();
            hienThiDanhSach();
        } catch (Exception e) {
        }
        //

    }
    //Kiểm tra textBox: 

    public boolean checkinfo() {
        Check c = new Check();
        if (!c.checkMaSv(txtMa.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập mã sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            txtMa.setText("");
            txtMa.requestFocus();
            return false;
        } else if (!c.checkSpace(txtHo.getText()) || !c.check(txtHo.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập tên sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            txtHo.setText("");
            txtHo.requestFocus();
            return false;

        } else if (!c.checkSpace(txtGioitinh.getText()) || !c.check(txtGioitinh.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập giới tính sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            txtGioitinh.setText("");
            txtGioitinh.requestFocus();
            return false;
        } else if (!c.checkSpace(txtKhoa.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập khoa sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            txtKhoa.setText("");
            txtKhoa.requestFocus();
            return false;

        }
        return true;
    }

    //Lấy danh sách sinh viên trên WamServer
    public ArrayList<SinhVien> LayDSSinhVien() {
        ArrayList<SinhVien> list = new ArrayList<>();
        try {
            Connection con = (Connection) DbKetNoi.Db.getConnection();
            Statement st = (Statement) con.createStatement();
            String sql = "SELECT * FROM sinhvien";
            //Thực thi : 
            ResultSet r = st.executeQuery(sql);

            SinhVien sv;

            while (r.next()) {

                sv = new SinhVien(r.getString("masv"), r.getString("hoten"),
                        r.getString("gioitinh"),
                        r.getInt("namthu"), r.getString("khoa"));

                list.add(sv);
            }
        } catch (Exception ex) {
            System.out.println("" + ex.getMessage());
        }
        return list;
    }

    //Hiển thi danh sách sinh viên : 
    public void hienThiDanhSach() {
        //Đẩy dữ liểu lên bảng:
        String co1tieude[] = new String[]{"ID", "Name", "Gender", "Year", "faculty"};

        ArrayList<SinhVien> list = LayDSSinhVien();
        DefaultTableModel model = new DefaultTableModel(co1tieude, 0);
        Object[] row;
        for (int i = 0; i < list.size(); i++) {
            row = new Object[5];

            //Gán giá trị : 
            row[0] = list.get(i).getMasv();
            row[1] = list.get(i).getHoten();
            row[2] = list.get(i).getGioitinh();
            row[3] = list.get(i).getNamthu();
            row[4] = list.get(i).getKhoa();

            model.addRow(row);

            //hien thi Jtable
            jTableSinhVien.setModel(model);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtMa = new javax.swing.JTextField();
        txtHo = new javax.swing.JTextField();
        txtNam = new javax.swing.JTextField();
        txtKhoa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtGioitinh = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSinhVien = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnResert = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtMa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtHo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtNam.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtKhoa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Mã Sinh Viên : ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Họ Tên : ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Năm Thứ : ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Khoa : ");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Giới tính : ");

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(txtHo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnSave)
                .addGap(199, 199, 199))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 51));
        jScrollPane1.setToolTipText("");
        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTableSinhVien.setBorder(new javax.swing.border.MatteBorder(null));
        jTableSinhVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MaSv", "HoTen", "Gioitinh", "Namthu", "Khoa"
            }
        ));
        jTableSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSinhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSinhVien);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnInsert.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new.png"))); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Update.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnResert.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnResert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reload.png"))); // NOI18N
        btnResert.setText("Resert");
        btnResert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInsert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnResert, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnResert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel5.setBackground(new java.awt.Color(51, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/graduated-icon (1).png"))); // NOI18N
        jLabel5.setText("BẢNG SINH VIÊN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
       
        try {
            Connection con = DbKetNoi.Db.getConnection();
            Statement st = (Statement) con.createStatement();
            //Câu truy vấn :
            String sql = "INSERT INTO sinhvien(masv, hoten, gioitinh , namthu , khoa) VALUES ('"
                    + txtMa.getText() + "','" + txtHo.getText() + "','"
                    + txtGioitinh.getText() + "','" + txtNam.getText() + "','"
                    + txtKhoa.getText() + "')";
            //Thực thi câu truy vấn :
            st.executeUpdate(sql);
            //Hiện thi trên danh sách :
            hienThiDanhSach();
            JOptionPane.showMessageDialog(null, "Thêm Thành Công ", "Thông Báo", 1);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Lỗi . Trùng MÃ SV ", "Thông Báo", JOptionPane.ERROR);
        }

        btnInsert.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        txtMa.setEnabled(true);
        btnResert.setEnabled(true);

    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        try {
            Connection con = DbKetNoi.Db.getConnection();
            Statement st = (Statement) con.createStatement();
            //Truy vấn update
            String sql = "UPDATE sinhvien SET masv = '" + txtMa.getText()
                    + "', hoten = '" + txtHo.getText()
                    + "', gioitinh = '" + txtGioitinh.getText()
                    + "', namthu = '" + txtNam.getText()
                    + "',khoa = '" + txtKhoa.getText()
                    + "' WHERE masv = '" + txtMa.getText()
                    + "'";

            //Thực thi truy vấn :
            st.executeUpdate(sql);
            //Kiểm tra dữ liêu:
            Check c = new Check();
            if (!checkinfo()) {
                return;
            }
            //Hiện thị danh sách:
            hienThiDanhSach();
            //Show kết quả :
            JOptionPane.showMessageDialog(null, "Cập nhập thêm công",
                    "Thông báo", 1);
        } catch (Exception ez) {
            JOptionPane.showMessageDialog(null, "Lỗi . Mã Sinh viên không tồn tại",
                    "Thông báo", JOptionPane.ERROR);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        //To change body of generated methods, choose Tools | Templates.
        try {
            Connection con = DbKetNoi.Db.getConnection();
            Statement st = (Statement) con.createStatement();
            //Truy vấn xóa sinh viên :
            String sql = "DELETE FROM sinhvien WHERE masv = '"
                    + txtMa.getText()
                    + "'";

            //Thực thi xóa:
            if (txtMa.getText() == null) {
                JOptionPane.showConfirmDialog(null, "Dữ liệu không thể xóa hoặc tồn tại ở bảng nào á");
            } else {
                st.executeUpdate(sql);
                hienThiDanhSach();
            }

            JOptionPane.showMessageDialog(null, "Xóa thành công", "Thông báo", 1);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error", "Thông báo", 2);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResertActionPerformed
        // TODO add your handling code here:

        //To change body of generated methods, choose Tools | Templates.
        txtMa.setText("");
        txtHo.setText("");
        txtGioitinh.setText("");
        txtNam.setText("");
        txtKhoa.setText("");
        txtMa.setEnabled(true);
        btnInsert.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnResertActionPerformed

    private void jTableSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSinhVienMouseClicked

        try {
            int i = jTableSinhVien.getSelectedRow();
            TableModel model = jTableSinhVien.getModel();

            txtMa.setText(model.getValueAt(i, 0).toString());
            txtHo.setText(model.getValueAt(i, 1).toString());
            txtGioitinh.setText(model.getValueAt(i, 2).toString());
            txtNam.setText(model.getValueAt(i, 3).toString());
            txtKhoa.setText(model.getValueAt(i, 4).toString());

            btnInsert.setEnabled(false);
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
            txtMa.setEnabled(false);
        } catch (Exception ee) {
            JOptionPane.showMessageDialog(null, "Cbưa có dữ liêu", "Thông báo", 1);
        }
    }//GEN-LAST:event_jTableSinhVienMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int i = chooser.showSaveDialog(chooser);
        if (i == JFileChooser.APPROVE_OPTION) {
            java.io.File file = chooser.getSelectedFile();
            try {
                FileWriter out = new FileWriter(file + ".xls");
                BufferedWriter bwrite = new BufferedWriter(out);
                DefaultTableModel model = (DefaultTableModel) jTableSinhVien.getModel();
                // ten Cot
                for (int j = 0; j < jTableSinhVien.getColumnCount(); j++) {
                    bwrite.write(model.getColumnName(j) + "\t");
                }
                bwrite.write("\n");
                // Lay du lieu dong
                for (int j = 0; j < jTableSinhVien.getRowCount(); j++) {
                    for (int k = 0; k < jTableSinhVien.getColumnCount(); k++) {
                        bwrite.write(model.getValueAt(j, k) + "\t");
                    }
                    bwrite.write("\n");
                }
                bwrite.close();
                JOptionPane.showMessageDialog(null, "Lưu file thành công!");
            } catch (Exception e2) {
                JOptionPane.showMessageDialog(null, "Lỗi khi lưu file!");
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnResert;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSinhVien;
    private javax.swing.JTextField txtGioitinh;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtKhoa;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtNam;
    // End of variables declaration//GEN-END:variables
}
